### ISSUE TITLE
Add world blacklist/whitelist

### ISSUE THREAD

**Issue by MatthewSH** [MatthewSH/spigot-RandomSpawn#7]
This feature is requested by [FireFlies](https://www.spigotmc.org/members/fireflies.301808/). So we need to add a new section to the configuration.

```
world-blacklist:
  fallback-world: world
  use-as-whitelist: false
  worlds:
    - ANameOfAWorld
```
